version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:postgresql://db:5432/lorenzoconsulting"
      DB_USERNAME: "test"
      DB_PASSWORD: "test"
    depends_on:
      - db

  db:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
      POSTGRES_DB: "lorenzoconsulting"
    volumes:
      - ./etc/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"