version: "3.7"

services:
  db:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
      POSTGRES_DB: "lorenzoconsulting"
    volumes:
      - ./etc/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"