spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lorenzoconsulting}
    username: ${DB_USERNAME:test}
    password: ${DB_PASSWORD:test}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/master.xml
