POST http://localhost:8080/reports
Content-Type: application/json

{
  "currency": "EUR",
  "fundedCapital": "Pepe",
  "nominalInterestRate": 2.17,
  "amortizationPeriod": 30,
  "amortizationSystem": "FRENCH"
}